# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: install phpDoc
      run: |
        wget https://phpdoc.org/phpDocumentor.phar
        chmod +x phpDocumentor.phar
        mv phpDocumentor.phar /usr/local/bin/phpDocumentor

    - name: generate_docs
      run: phpdoc --config ./phpdoc.xml

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages-docs
        build_dir: ./docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
