name: Build docs

on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install phpDoc
      run: |
        wget https://phpdoc.org/phpDocumentor.phar
        chmod +x phpDocumentor.phar
        mv phpDocumentor.phar /usr/local/bin/phpDocumentor
        pwd
        echo `ls`

    - name: generate docs
      run: phpDocumentor --config phpdoc.xml

    - name: Deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs
